version: "3.8"
services:
  mongodb:
    container_name: mongo-service
    image: mongo:latest
    volumes:
      - .backend/data:/data
    ports:
      - "27017:27017"

  backend:
    container_name: backend-service
    build: ./backend
    env_file:
      - ./backend/.env.docker
    ports:
      - "31100:8080"
    depends_on:
      - mongodb

  frontend:
    container_name: frontend-service
    build: ./frontend
    env_file:
      - ./frontend/.env.docker
    ports:
      - "5173:5173"
    depends_on:
      - backend

  redis:
    container_name: redis-service
    image: redis:7.0.5-alpine
    ports:
      - "6379:6379"
    depends_on:
      - mongodb
