apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
  namespace: app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: nishargsoni/wanderlust-backend-beta:v6
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
  namespace: app
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31100
  type: NodePort
